baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

sass:
  sass_dir: assets/scss
  style: compressed

# Collections

collections:
  hubs:
    output: true
    output_ext: .html
    permalink: /hubs/:path/
  highlights:
    output: true
    permalink: /highlights/:title/
  stories:
    output: true
    permalink: /stories/:title/
  resources:   # remove??
    output: true
    output_ext: .html
    permalink: /resources/:path/
  tools:   # remove??
    output: true
    output_ext: .html
    permalink: /tools/:path/

defaults:
  - scope:    # set standard layout for all posts in a collection
      path: ""
      type: highlights
    values:
      layout: page
  - scope:    # set standard layout for all posts in a collection
      path: ""
      type: stories
    values:
      layout: page

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.text
  - README.md
  - SECURITY.md
