#-------------------------------
# General Site Settings

title: '#ASKnet'
logo: /assets/img/asknet-logo.png
author: '#ASKnet'
description: "Access to Skills & Knowledge network"
email: coordinator@asknet.community
phone: 
address: 
screenshot: https://raw.githubusercontent.com/ASKnetCommunity/ASKnet.Community/51b8d4f7a3a772eb2a55968b721b98bb657db161/screenshot.png

menu:
- name: About
  link: '/#about'
- name: Members
  link: '/#members'
- name: Our Story
  link: '/#timeline'
- name: Resources
  link: ''
  sub: 
    - name: About Open Educational Resources
      link: '/oer'
    - name: '#ASKnet Platforms'
      link: '/asknet-platforms'
    - name: '#ASKnet Tools'
      link: '/tools'
    # - name: '#ASKnet Highlights'
    #   link: '/highlights'
    - name: '#ASKnet Member Stories'
      link: '/member-stories'
- name: Contact
  link: '/#contact'



#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: "Welcome to #ASKnet"
  hero-subtitle: The ACCESS to SKILLS & KNOWLEDGE network
  hero-button-text: LEARN MORE
  hero-button-link: "#about"

social:
- {icon: "ti-facebook", link: "#"}
- {icon: "ti-instagram", link: "#"}
- {icon: "ti-dribbble", link: "#"}
- {icon: "ti-twitter", link: "#"}

#-------------------------------
# About Section

about-title: "#ASKnet<br />The Access to Skills & Knowledge network"
about-description: "#ASKnet is a cross-border consortium of community driven organizations. The network provides access to a range of open source knowledge and information, media and IT related training as well as community oriented hands-on skills."
about:
- {name: '#ASKnet is a network of hubs and community members,', icon: 'fas fa-project-diagram' }
- {name: 'founded by young South Sudanese innovators,', icon: 'fas fa-lightbulb' }
- {name: 'governed by a Steering Committee drawn from all of its member organizations,', icon: 'fas fa-users' }
- {name: 'to build a transformative and sustainable media development ecosystem.', icon: 'fas fa-photo-video' }
about-description-2: | 
  ### Vision 

  A connected, creative, and open society where knowledge flows freely, empowering communities to shape their own futures by building a transformative and sustainable media ecosystem.

  ### Mission

  #ASKnet builds bridges between media, technology, and community action. We strengthen youth-led innovation, share open knowledge, and grow local capacity through peer to peer training, open tech innovation, collaboration, and creativity across borders.

  ### Who We Are

  Born from a network of South Sudanese innovators, #ASKnet links community hubs and changemakers across the region. Together, we use media, technology, and peer learning to solve local challenges, create livelihoods, and amplify community voices.

  Supported by r0g_agency (Berlin) and Hive Colab (Kampala), with funding from the German Federal Ministry for Economic Cooperation and Development (BMZ), 2022–2025.
about-profile-button-title: "Our Organizational Framework"


#-------------------------------
# focus-areas Section

focus-areas-title: Focus Areas
focus-areas:
- {
    name: Community Empowerment,
    icon: fas fa-users,
    description: 'We connect people and ideas to build resilient, knowledge-sharing communities, from towns and villages to refugee settlements.',
    active: # Add true to select section
  }
- {
    name: Media for Democracy,
    icon: fas fa-laptop,
    description: 'We foster media literacy and storytelling that strengthen accountability, civic engagement, and peacebuilding.',
    active: # Add true to select section
  }
- {
    name: Open Culture,
    icon: fab fa-osi,
    description: 'We champion open access to tools, resources, and skills. Sharing knowledge creates pathways to new opportunities, entrepreneurship, livelihood, equality and collaboration.',
    active: # Add true to select section
  }


#-------------------------------
# Member Hubs Section

hub-section-title: "Members <div class=\"h4\" style=\"font-weight: normal;\">(November 2025)</div>"
hub-section-description: |
  The member organizations have a community-led focus and contribute to strengthening civil society structures in South Sudan, while creating a basis for strengthened communication and cooperation, especially between communities of refugees in neighbouring countries together with those in South Sudan.
hub-section-contact: "Are you interested in becoming a member? Get in contact with us!"

#-------------------------------
# Timeline Section

timeline:
  title: "Our Story"
  text: |
    #### Where do we come from?

    Building on the context from which #ASKnet emerged as an initiative for improved access to information, media literacy and proactive peacebuilding, a cross-border network of peers and experts is now evolving into an independent, self-sufficient network.

  section: timeline
  # left is the default
  #start_align: "left"
  events:
    - title: "The jHUB Pioneers"
      year: "2015"
      desc: "Community media trainings with participants from around South Sudan drafted and signed a Charter of Common Values, sparking the creation of the Juba Open Knowledge & Innovation Hub (jHUB) and co-creation of the first #peacehackcamp in South Sudan."
      image: assets/img/timeline/2015.jpg
      alt:
      url: https://openculture.agency/peacehackcamp-2015/
    - title: "Migrations & New Horizons"
      year: "2016"
      desc: 'As conflict spreads, members relocate across East Africa, developing the #ASKotec kit and planting the seeds of today’s #ASKnet.'
      image: assets/img/timeline/2016.jpg
      alt:
      url:
    - title: "New Members Emerge"
      year: "2017"
      desc: 'New informal organisations are established and launched by former jHUB members to create local hubs and teach skills in local contexts and refugee settlements, such as Rhino Camp in Northern Uganda, and towns in South Sudan such as Bor.'
      image: assets/img/timeline/2017.jpg
      alt:
      url:
    - title: "A Growing Network"
      year: "2018"
      desc: "#ASKnet takes shape as an informal collaboration of media makers and open tech innovators across the region. A first collective training session on Media, IT, Open Tech innovation and repair culture held in Rhino Camp South Sudanese refugee settlement."
      image: assets/img/timeline/2018.jpeg
      alt:
      url:
    - title: "From Hubs to Community"
      year: "2019"
      desc: "Six legally registered hubs unite as the first #ASKnet collective; in collaboration with the Global Innovation Gathering (GIG) first international #ASKsummit (DOTS) held in Kenya."
      image: assets/img/timeline/2019.jpg
      alt:
      url:
    - title: "Decentralized Action"
      year: "2020"
      desc: "In response to COVID-19, #ASKnet shifts to online training and mentoring to connect media and tech hubs across borders with the emerging community of #ASKnet experts."
      image: assets/img/timeline/2020.jpg
      alt:
      url:
    - title: "Strengthening Local Impact"
      year: "2021"
      desc: "Hubs expand community programs and life skills trainings in South Sudan and Uganda. The “Labmobile” is launched at Rhino Camp, and #ROSHOP modular housing prototype at Pagirinya Refugee Settlement in Uganda joins the expanding resources and programs."
      image: assets/img/timeline/2021.jpg
      alt:
      url:
    - title: "Founding the Consortium"
      year: "2022 / 2023"
      desc: "#ASKnet formalizes as an international consortium, a self-governed, inclusive cross-border network of South Sudanese led youth-led media and innovation hubs."
      image: assets/img/timeline/2022.jpg
      alt:
      url:
    - title: "Expanding Reach"
      year: "2024"
      desc: "New partnerships and open culture initiatives strengthen collaboration and OER development across the network, and the launch of the #ASKtraining platform."
      image: assets/img/timeline/2024.jpg
      alt:
      url:
    - title: "13 Hubs Strong"
      year: "2025"
      desc: "#ASKnet grows to 13 member organisations, each advancing local independence and innovation within their communities."
      image: assets/img/timeline/2025.jpg
      alt:
      url:
    - title: "The Future Is Open"
      year: "2026"
      desc: "The network continues to expand, welcoming new communities to co-create, collaborate, and share open knowledge for resilience, empowerment and transformation."
      image: assets/img/timeline/2026.jpg
      alt:
      url:
    # you can enforce the alignment: 
    # align: right
  # end: 
  #   title: "Add new training, event, or project!"
  #   link: "https://github.com/ASKnetCommunity/ASKnet.Community/issues/new?assignees=&labels=content-submit%2Cnew-timeline-event&template=new-timeline-event.yml&title=Add+Timeline+Event%3A+"


#-------------------------------
# LEAD Section

lead-title: "#ASKlead"
lead-description: |
  Many of the #ASKnet members and their communities have undergone training of trainer programs and peer-to-peer learning in self-taught formats, developed collaboratively through workshops and programs run by the initiative.
  
  The #ASKnet Local Expert Action Directory (LEAD) is a growing and functioning tool to connect people who have specific expertise and skills in media, ICT, and a range of various technologies with important backgrounds on local and regional contexts - be they storytelling, videography, device repair, software programming, or mechanical skills with potential clients, other community members, and all those seeking advice and information about youth-led South Sudanese innovation culture.

lead-button-title: "Go to LEAD"
lead-button-link: "https://lead.asknet.community/"

#-------------------------------
# Resources Section

resources-title: "#ASKnet Tools and Resources"
resources-description: |
  The #ASKnet and community members curate and share Open Learning Guides, toolkits, and resources from their work so that others can adopt, adapt and deploy them in their own communities to promote local innovation and peer-to-peer knowledge exchange.
resources-sub-sections: 
  - { title: "#ASKtraining", text: "An initial prototype of the #ASKtraining platform, to be used to compile, share and streamline the running of workshops, learning content and deliver ‚how to‘ instructions is created to make training easier and more accessible. In this way, experiential knowledge is secured, which improves the sustainability of activities and facilitates the induction of new members and participants.", image-url: "assets/img/tools/training.jpg", button-text: "Go To #ASKtraining", button-url: "https://training.asknet.community/", button-is-internal: false }
  - { title: "#ASKotec", text: "#ASKotec - the ‘Access to Skills and Knowledge open tech emergency case’ is a resource kit for community trainers that is designed as a light and handy mobile workshop creation set, equipped with a broad range of items needed to teach others. The kit is especially valuable to communities where access to tools, power and materials is often scarce.", image-url: "assets/img/resources/askotec.jpg", button-text: "More about #ASKotec", button-url: "https://askotec.openculture.agency/", button-is-internal: false }
  - { title: "#OpenGuides", text: "#ASKnet has so far released five ‘OpenGuides’, providing beginners and advanced users with methods and strategies to apply open culture principles more effectively - opening doors to new creative opportunities for collaboration, learning and developing new skills.", image-url: "assets/img/resources/open-guides.png", button-text: "view Open Guides", button-url: "open-guides", button-is-internal: true }


#-------------------------------
# Tools Section

# tools-title: "#ASKTOOLS"
# tools-description: "


#-------------------------------
# Client Slider Section
  
client-slider-items:    

  - logo: assets/img/clients/r0g_logo.png
    url: https://openculture.agency/

  - logo: assets/img/clients/founder_BMZ.jpg
    url: https://www.bmz.de/en

  - logo: assets/img/clients/hive_colab.png
    url: https://hivecolab.org/

  - logo: assets/img/hubs/01-platform-africa-asknet-logo.png
    url: https://www.platformafrica.ngo/

  - logo: assets/img/hubs/02-gogirls-ict-juba-asknet-logo.png
    url: https://gogirlsict.org/

  - logo: assets/img/hubs/03-junub-open-space-juba-asknet-logo.png
    url: https://junubos.org/

  - logo: assets/img/hubs/05-youth-empowerment-yef-asknet-logo.png
    url: https://yef-uganda.org/

  - logo: assets/img/hubs/06-CC4D-asknet-logo.jpg
    url: https://cc4d.tech/

  - logo: assets/img/hubs/07-mamara-sakit-logo.jpg
    url: https://mamarasakitvillage.org/

  - logo: assets/img/hubs/08-CECI-Uganda-Logo.png
    url: https://www.ceciuganda.org/

  - logo: assets/img/hubs/09-CIC-logo.jpg
    url: https://www.facebook.com/profile.php?id=100076026173627

  - logo: assets/img/hubs/10-koneta-hub-logo.png
    url: https://konetahub.org/

  - logo: assets/img/hubs/CSCOV-logo.jpg
    url: https://cscov-ss.org/

  - logo: assets/img/hubs/KVA-logo.jpg
    url: https://www.kvadvocates.org

#-------------------------------
# Contact-Section

contact-title: Contact Info
contact-text: |
  <p>For general information about the network please contact our #ASKnet – Network Coordination in Juba by email: <script language="JavaScript" type="text/javascript">
  var part1 = "coordinator";
  var part2 = Math.pow(2,6);
  var part3 = String.fromCharCode(part2);
  var part4 = "asknet.community";
  var part5 = part1 + String.fromCharCode(part2) + part4;
  document.write("<a href=\"" + "mai" + "lto" + ":" + part5 + "\">" + part1 + part3 + part4 + "</a>");
  </script></p>
  <p>#ASKnet is supported by r0g_agency (Berlin, Germany) and Hive Colab (Kampala, Uganda) as implementing partners.</p>
  <p>#ASKnet 2022-2025 is funded by the German Ministry for Economic Development and Cooperation (BMZ).</p>

contact-email: coordinator@asknet.community
formspree-path: f/myylarkr

#-------------------------------
# Media Page

media-items:
  podcasts:
  - title: Refugee Youth Podcast
    image-url: assets/img/media-page/ryp-logo.jpg
    by-hub-name: Youth Empowerment Foundation
    by-hub-link: /hubs/yef
    text: A series dedicated to sharing the stories and experiences of refugees living in Northern Uganda. Produced and hosted by young refugees in the Pagirinya refugee settlement near Adjumani, Uganda experiences and stories are shared with the aim of educating, informing, and strengthening resilience within the community.
    link1-url: https://on.soundcloud.com/RMwXEqY6LbAseCBx8
    link1-platform: SoundCloud

  - title: Amplified Gender Voices 
    image-url: assets/img/media-page/agvpodcast-logo.jpeg
    by-hub-name: GoGirls ICT Initiative
    by-hub-link: /hubs/gogirls-ict
    text: Every woman’s story is a powerful force for change. In this podcast, the Juba-based GoGirlsICT community brings you inspiring stories, thought-provoking interviews, and impactful conversations that shine a light on how the women of South Sudan overcome deeply rooted societal challenges. <br><br> <a href="https://feeds.soundcloud.com/users/soundcloud:users:1289645559/sounds.rss" target="_blank">RSS Feed</a>
    link1-url: https://soundcloud.com/agvpodcast
    link1-platform: SoundCloud

  - title: Classroom on Phone 
    image-url: assets/img/media-page/cop-logo.jpg
    by-hub-name: GoGirls ICT Initiative
    by-hub-link: /hubs/gogirls-ict
    text: A pre-recorded series of learning programs, easily accessible through smart phones, where primary and secondary school students are taught a range of STEM subjects (Science, Technology, Engineering and Mathematics) with the aim of enhancing the love and practice of science. <br><br> <a href="https://feeds.soundcloud.com/users/soundcloud:users:1289645559/sounds.rss" target="_blank">RSS Feed</a><br><br> <a href="https://www.youtube.com/@gogirlsictinitiative4202" target="_blank">Feedback on Classroom on Phones series implementation in schools</a>
    link1-url: https://soundcloud.com/classroom-on-phone
    link1-platform: SoundCloud
    link2-url: https://podcasters.spotify.com/pod/show/classroomonphone/episodes/ClassroomOnPhone-Series-GoGirls-learning-Podcast-ergreh
    link2-platform: Spotify

  - title: "#ASK&shy;podcast" 
    image-url: assets/img/media-page/askpodcast-cover.jpg
    by-external-name: "#ASKnet member Romeo Lomoro"
    by-external-link: https://lead.asknet.community/profiles/Romeo-Lomora-Ronald/
    text: This is where technology meets community, and innovation solves problems. Join us as we delve into the world of open technology and explore the impact it has on communities in South Sudan and Uganda. Through the eyes and voices of local organizations, community leaders, and individuals, we bring you the stories of change-makers who are using technology to create a better future for their communities. <br><br> <a href="https://www.youtube.com/@_ASKnet" target="_blank">#ASKnet Video Stream Conversations</a>
    link1-url: https://podcasters.spotify.com/pod/show/ask-podcast6
    link1-platform: Spotify
    link2-url: https://www.jiosaavn.com/shows/ask-podcast/2/pV8HqsZcUAI_
    link2-platform: JioSaavn

  - title: Refutories 
    image-url: assets/img/media-page/refutories-cover.jpg
    by-hub-name: Platform Africa
    by-hub-link: /hubs/platform-africa
    text: "“Refutories” is a word that emanates from Refugee Stories, telling these through interviews with refugees in the Rhino Camp settlement near Arua, Uganda. Their daily experiences with access to education and the numerous struggles faced living in the refugee settlement, the podcast looks at issues ranging from sex education to the many cultural aspects displaced people must face on a daily basis."
    link1-url: https://on.soundcloud.com/QAbKZCdG9wY34Nos6
    link1-platform: SoundCloud
  
  videos:
  - title: E-Waste Awareness
    image-url: assets/img/media-page/ewa-cover.png
    by-hub-name: Community Creativity 4 Development
    by-hub-link: /hubs/cc4d
    text: Highlighting refugee innovation in tackling the problem of e-waste management through training and awareness on repair, reuse, and upcycling projects the video was produced in support of the global International Repair Day.
    link1-url: https://www.youtube.com/watch?v=Zt4bFndoXM0
    link1-platform: YouTube

    # Template: 
      # - title: Refugee Youth Podcast
      #   image-url: assets/img/media-page/ryp-logo.jpg
      #   by-hub-name: Youth Empowerment Foundation
      #   by-hub-link: /hubs/yef        # refers to the name of the hub file, e.g. yef.md
      #   by-external-name:             # if it's not a hub but something else and the link should go to an external site. delete this and the next line if not applicable. If applicable, delete the two lines above.
      #   by-external-link: 
      #   text: A series dedicated to sharing the stories and experiences of refugees living in Northern Uganda. Produced and hosted by young refugees in the Pagirinya refugee settlement near Adjumani, Uganda experiences and stories are shared with the aim of educating, informing, and strengthening resilience within the community.
      #   link1-url: https://on.soundcloud.com/RMwXEqY6LbAseCBx8      # one or two links can be there per media-item. if just one link, delete the "link2-..." lines
      #   link1-platform: SoundCloud
      #   link2-url: https://on.soundcloud.com/RMwXEqY6LbAseCBx8
      #   link2-platform: SoundCloud