#-------------------------------
# General Site Settings

title: '#ASKnet'
logo: assets/img/asknet-logo.png
author: '#ASKnet'
description: "Access to Skills & Knowledge network"
email: coordinator@asknet.community
phone: 
address: 
screenshot: https://raw.githubusercontent.com/ASKnetCommunity/ASKnet.Community/51b8d4f7a3a772eb2a55968b721b98bb657db161/screenshot.png

menu:
- {name: About, link: '/#about'}
- {name: Members, link: '/#members'}
- {name: Experts, link: '/#lead'}
- {name: Resources, link: '/#resources'}
- {name: Media, link: '/media'}
# - {name: "#ASKtools", link: '/#asktools'}
- {name: Our Story, link: '/#timeline'}
- {name: Contact, link: '/#contact'}



#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: "Welcome to #ASKnet"
  hero-subtitle: The ACCESS to SKILLS & KNOWLEDGE Network
  hero-button-text: LEARN MORE
  hero-button-link: "#about"

social:
- {icon: "ti-facebook", link: "#"}
- {icon: "ti-instagram", link: "#"}
- {icon: "ti-dribbble", link: "#"}
- {icon: "ti-twitter", link: "#"}

#-------------------------------
# About Section

about-title: "#ASKnet<br />The Access to Skills & Knowledge network"
about-description: "#ASKnet is a cross-border consortium of community driven organizations with an aim to build a transformative and sustainable open society and a professional media skills ecosystem. The network provides access to a range of open source knowledge and information, media and IT related training as well as community oriented hands-on skills."
about:
- {name: '#ASKnet is a network of hubs and community members,', icon: 'fas fa-project-diagram' }
- {name: 'founded by young South Sudanese innovators,', icon: 'fas fa-lightbulb' }
- {name: 'governed by a Steering Committee drawn from all of its member organizations,', icon: 'fas fa-users' }
- {name: 'to build a transformative and sustainable media development ecosystem.', icon: 'fas fa-photo-video' }
about-description-2: "The nine members of #ASKnet address local community challenges, support empowerment with knowledge and skills, inspire regional innovation and creativity, and engage peacebuilding and community empowerment among all members of society."
about-description-3: "#ASKnet is supported by r0g_agency (Berlin, Germany) and Hive Colab (Kampala, Uganda) as implementing partners. The project in the period of 2022-2025 is funded by the German Ministry of Economic Development and Cooperation (BMZ)."
about-profile-button-title: "Our Organizational Framework"


#-------------------------------
# Services Section

services-title: Services
services:
- {
    name: Community,
    icon: fas fa-users,
    description: 'We bring together people and ideas to help build resilient environments for strong knowledge exchange within numerous communities - in towns, villages, and local neighborhoods, including within refugee or IDP settlements. We strive to harness and make public the collective knowledge and skills of local experts, refugees, activists, and CSOs to deepen local impact and create opportunities for mutual support and collaboration.',
    active: # Add true to select section
  }
- {
    name: Media Literacy,
    icon: fab fa-osi,
    description: '#ASKnet embraces the philosophy of open knowledge sharing and encourages its community to openly share their work and invite others to engage and learn from it as a means to break down silos and barriers to learning. This catalyzes collaboration, peer-to-peer exchange, and civic engagement, strengthening and creating paths to new opportunities, entrepreneurship, and further networks of skills and resources.',
    active: # Add true to select section
  }
- {
    name: Media Development,
    icon: fas fa-laptop,
    description: '#ASKnet contributes to create an environment where the media plays a constructive role in fostering democracy, accountability, and public participation. Education about media literacy is crucial and involves helping individuals critically evaluate and understand the media they consume, discerning reliable information from misinformation.',
    active: # Add true to select section
  }


#-------------------------------
# Member Hubs Section

hub-section-title: "#ASKnet Members <div style=\"font-weight: normal;\">(November 2023)</div>"
hub-section-description: |
  The member organizations have a community-led focus and contribute to strengthening civil society structures in South Sudan, while creating a basis for strengthened communication and cooperation, especially between communities of refugees in neighbouring countries together with those in South Sudan. 
 
  - CC4D - Community Creativity for Development (Rhino Camp, Uganda)
  - CECI - Community Empowerment For Creative Innovation (Koboko, Uganda)
  - CIC - Creative Innovation Center (Rhino Camp, Uganda)
  - GoGirls ICT Initiative (Juba, South Sudan)
  - Junub Open Space (Juba, South Sudan)
  - Koneta Hub (Juba, South Sudan)
  - Ma'Mara Sakit (Juba, South Sudan)
  - Platform Africa (Rhino Camp, Uganda)
  - YEF - Youth Empowerment Foundation (Adjumani / Pagirinya, Uganda)

hub-section-contact: "Are you interested to become a member? Get in contact with us!"

#-------------------------------
# Timeline Section

timeline:
  title: "Our Story"
  text: |
    #### Where do we come from?

    Building on the context from which #ASKnet emerged as an initiative for improved access to information, media literacy and proactive peacebuilding, a cross-border network of peers and experts is now evolving into an independent, self-sufficient network.

  section: timeline
  # left is the default
  #start_align: "left"
  events:
    - title: "The jHUB ‘Pioneers’"
      year: "2015"
      desc: "The program started with a series of community-based media trainings. The participants, hailing from various parts of South Sudan, drafted and signed a Charter of Common Values, launching the Juba Open Knowledge and Innovation Hub (jHUB). Later that year the jHUB community co-created the first #peacehackcamp!"
      image: assets/img/timeline/2015.jpg
      alt: 
      url: https://openculture.agency/peacehackcamp-2015/
    - title: "Migrations, New Horizons"
      year: "2016"
      desc: 'As armed conflict erupted again in South Sudan, the community scattered, with some members taking refuge in neighboring countries. Hosting of trainings were taken on by partners in Addis Ababa, Nairobi, Kigali, Kampala. The #ASKotec kit was developed and a network of local initiatives that has since evolved into what is now #ASKnet.'
      image: assets/img/timeline/2016.jpg
      alt:
      url: https://github.com/ASKnetCommunity/ASKnet.Community
    - title: "New Members"
      year: "2017"
      desc: 'A number of new, initially informal organizations were established and launched by former jHUB members, who began sharing various skills with local participants in their specific contexts. These also included refugee settlements such as Rhino Camp in Northern Uganda, and towns in South Sudan such as Bor.'
      image: assets/img/timeline/2017.jpg
      alt: 
      url: 
    - title: "An Informal Network"
      year: "2018"
      desc: "#ASKnet emerges as an informal network as a collaboration of media organizations and local experts starts to grow. A first collective training session, focused on Media, IT, Open Tech innovation and repair culture was held in the Rhino Camp South Sudanese refugee settlement."
      image: assets/img/timeline/2018.jpeg
      alt: 
      url: 
    - title: "Community Practices"
      year: "2019"
      desc: "Six ‚pioneer‘ hubs, all legally registered organizations, form the first collective #ASKnet community. In collaboration with the Global Innovation Gathering (GIG) with members coming together from 5 continents, DOTS, the first international #ASKnet summit was held in Nakuru, Kenya."
      image: assets/img/timeline/2019.jpg
      alt: 
      url:
    - title: "Decentralized Actions"
      year: "2020"
      desc: "In response to the Covid-19 pandemic, #ASKnet evolves from hosting local trainings to a more decentralized network of online activity. With the online training and mentoring ‚tracks‘ - focusing on organizational development and on digital media and open tech skills, a community of individual #ASKnet experts, as well as formalized media hubs emerged."
      image: assets/img/timeline/2020.jpg
      alt: 
      url: 
    - title: "Hub Strengthening"
      year: "2021"
      desc: "#ASKnet hubs increase their own community engagement, with a broad range of media and life skills training, also helping to empower more community members in need of support and attention. The ‚Labmobile‘ at Rhino Camp, and an locally sourced housing prototype at the Pagirinya Refugee Settlement in Uganda join a family of resources and programs established earlier in South Sudan."
      image: assets/img/timeline/2020.jpg
      alt: 
      url: 
    - title: "Founding an International Innovation Consortium"
      year: "2022 / 2023"
      desc: "Adaptation of the informal international #ASKnet group of hubs into a consortium, with a legal registration in South Sudan. Foundations are laid for an inclusive cross-border and self-governed network of South Sudanese led youth-led media and innovation organizations able and open to bring on more members."
      image: assets/img/timeline/2020.jpg
      alt: 
      url: 
    # you can enforce the alignment: 
    # align: right
  # end: 
  #   title: "Add new training, event, or project!"
  #   link: "https://github.com/ASKnetCommunity/ASKnet.Community/issues/new?assignees=&labels=content-submit%2Cnew-timeline-event&template=new-timeline-event.yml&title=Add+Timeline+Event%3A+"

#-------------------------------
# LEAD Section

lead-title: "#ASKlead"
lead-description: |
  Many of the #ASKnet members and their communities have undergone training of trainer programs and peer-to-peer learning in self-taught formats, developed collaboratively through workshops and programs run by the initiative.
  
  The #ASKnet Local Expert Action Directory (LEAD) is a growing and functioning tool to connect people who have specific expertise and skills in media, ICT, and a range of various technologies with important backgrounds on local and regional contexts - be they storytelling, videography, device repair, software programming, or mechanical skills with potential clients, other community members, and all those seeking advice and information about youth-led South Sudanese innovation culture.

lead-button-title: "Go to LEAD"
lead-button-link: "https://lead.asknet.community/"

#-------------------------------
# Resources Section

resources-title: "#ASKnet Tools and Resources"
resources-description: |
  The #ASKnet and community members curate and share Open Learning Guides, toolkits, and resources from their work so that others can adopt, adapt and deploy them in their own communities to promote local innovation and peer-to-peer knowledge exchange.
resources-sub-sections: 
  - { title: "#ASKtraining", text: "An initial prototype of the #ASKtraining platform, to be used to compile, share and streamline the running of workshops, learning content and deliver ‚how to‘ instructions is created to make training easier and more accessible. In this way, experiential knowledge is secured, which improves the sustainability of activities and facilitates the induction of new members and participants.", image-url: "assets/img/tools/training.jpg", button-text: "Go To #ASKtraining", button-url: "https://training.asknet.community/training/", button-is-internal: false }
  - { title: "#ASKotec", text: "#ASKotec - the ‘Access to Skills and Knowledge open tech emergency case’ is a resource kit for community trainers that is designed as a light and handy mobile workshop creation set, equipped with a broad range of items needed to teach others. The kit is especially valuable to communities where access to tools, power and materials is often scarce.", image-url: "assets/img/resources/askotec.jpg", button-text: "More about #ASKotec", button-url: "https://askotec.openculture.agency/", button-is-internal: false }
  - { title: "#OpenGuides", text: "#ASKnet has so far released five ‘OpenGuides’, providing beginners and advanced users with methods and strategies to apply open culture principles more effectively - opening doors to new creative opportunities for collaboration, learning and developing new skills.", image-url: "assets/img/resources/open-guides.png", button-text: "view Open Guides", button-url: "open-guides", button-is-internal: true }


#-------------------------------
# Tools Section

tools-title: "#ASKTOOLS"
tools-description: ""


#-------------------------------
# Client Slider Section
  
client-slider-items:    

  - logo: assets/img/clients/r0g_logo.png
    url: https://openculture.agency/

  - logo: assets/img/clients/founder_BMZ.jpg
    url: https://www.bmz.de/en

  - logo: assets/img/clients/hive_colab.png
    url: https://hivecolab.org/

  - logo: assets/img/hubs/01-logo.png
    url: https://www.platformafrica.ngo/

  - logo: assets/img/hubs/02-logo.png
    url: https://gogirlsict.org/

  - logo: assets/img/hubs/03-logo.png
    url: https://junubos.org/

  - logo: assets/img/hubs/05-logo.png
    url: https://yef-uganda.org/

  - logo: assets/img/hubs/06-CC4D-asknet-logo.png
    url: https://cc4d.tech/

  - logo: assets/img/hubs/07-mamara-logo.jpg
    url: https://mamarasakitvillage.org/

  - logo: assets/img/hubs/08-CECI-Uganda-Logo.png
    url: https://www.ceciuganda.org/

  - logo: assets/img/hubs/09-CIC-logo.jpg
    url: https://www.facebook.com/profile.php?id=100076026173627

  - logo: assets/img/hubs/10-koneta-logo.png
    url: https://konetahub.org/

#-------------------------------
# Contact-Section

contact-title: Contact Info
contact-text: |
  For general information about the network please contact our #ASKnet – Network Coordination in Juba by email: <a href="mailto:coordinator@asknet.community">coordinator@asknet.community</a>.
  
  #ASKnet is supported by r0g_agency (Berlin, Germany) and Hive Colab (Kampala, Uganda) as implementing partners.
  
  #ASKnet  2022-2025 is funded by the German Ministry of Economic Development and Cooperation (BMZ).

contact-email: coordinator@asknet.community
formspree-path: f/myylarkr
