blank_issues_enabled: true
contact_links:
  - name: Blank issue
    url: https://github.com/ASKnetCommunity/ASKnet.Community/issues/new
    about: Anything else? Before opening a new issue, please search for the problem/topic in the existing issues.
